apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
data:
  # These values should be base64 encoded
  sql_alchemy_conn: <base64_encoded_connection_string>
  fernet_key: <base64_encoded_fernet_key> 
